services:
  - type: web
    name: uchat-render
    env: rust
    plan: free
    buildCommand: cargo build --release
    startCommand: ./target/release/uchat-render
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /